version: '3.9'

services:
  scanner-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitoring_uvicorn
    environment:
      - BACKUP_STORAGE_ROOT=/mnt/backups
      - VALIDATED_BACKUPS_BASE_PATH=/mnt/validated
    volumes:
      - ./backup-data:/mnt/backups
      - ./validated-backups:/mnt/validated
      - ./data/db:/monitoring/data/db
    ports:
      - "8000:8000"
    restart: always
