version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - backup_storage:/mnt/backups
      - sqlite_data:/app/data/db
    environment:
      DATABASE_URL: "sqlite:///./data/db/sql_app.db"
      SMTP_SERVER: "smtp.example.com"
      SMTP_PORT: "587"
      SMTP_USER: "your_email@example.com"
      SMTP_PASSWORD: "your_email_password_here"

volumes:
  backup_storage:
  sqlite_data:
