# Configuration du système de logging de l'application.

version: 1 # Version du schéma de configuration du logging
disable_existing_loggers: False # Ne pas désactiver les loggers Python existants

formatters: # Définition des formats de message pour les logs
  standard: # Formateur standard pour la console et les fichiers
    format: '[%(asctime)s] - [%(name)s] - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  detailed: # Formateur plus détaillé, utile pour les logs de debug ou spécifiques
    format: '[%(asctime)s] - [%(name)s:%(lineno)d] - %(levelname)s - %(threadName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

handlers: # Définition des destinations des logs (où les messages sont envoyés)
  console: # Handler pour afficher les logs dans la console
    class: logging.StreamHandler
    formatter: standard
    level: INFO # N'affiche que les messages de niveau INFO ou supérieur dans la console
    stream: ext://sys.stdout # Envoie à la sortie standard (console)

  file_handler: # Handler pour écrire les logs dans un fichier
    class: logging.handlers.RotatingFileHandler
    formatter: standard
    level: DEBUG # Enregistre tous les messages (DEBUG ou supérieur) dans le fichier
    filename: logs/app.log # Le nom du fichier de log. Ce chemin est relatif au WORKDIR dans Docker.
    maxBytes: 10485760 # Taille maximale du fichier (10 Mo) avant rotation
    backupCount: 5 # Nombre de fichiers de log de sauvegarde à conserver

loggers: # Définition des loggers spécifiques de l'application
  app: # Logger pour le code de votre application (ex: app.main, app.services, etc.)
    handlers: [console, file_handler]
    level: DEBUG # Niveaux de log par défaut pour les modules de l'application (peut être surchargé par module)
    propagate: False # Empêche les messages d'être passés au logger root (si défini ailleurs)

root: # Le logger racine (root logger) de Python
  handlers: [console] # Seuls les messages importants des autres librairies sont envoyés à la console
  level: INFO # Niveau INFO par défaut pour les librairies tierces